// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type APK struct {
	Package     string `json:"package"`
	ArtifactKey string `json:"artifactKey"`
	VersionName string `json:"versionName"`
	VersionCode string `json:"versionCode"`
}
