// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Asset struct {
	Confidences []Confidence `json:"confidences"`
	Confidence  *int         `json:"confidence"`
	NeedsReview *bool        `json:"needsReview"`
	ASNumber    string       `json:"asnumber"`
	ASName      string       `json:"asname"`
	Capability  []string     `json:"capability"`
	DNS         string       `json:"dns"`
	Name        string       `json:"name"`
}

type Confidence struct {
	Score         int    `json:"score"`
	Justification string `json:"justification"`
}
