// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

// SpecFormat constants are the allowed values for WebApplication.SpecFormat.
const (
	SpecFormatOpenAPI = "openapi"
	SpecFormatGraphQL = "graphql"
	SpecFormatWSDL    = "wsdl"
)
