// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Person struct {
	FirstName         string          `json:"first_name"`
	LastName          string          `json:"last_name"`
	Email             string          `json:"email"`
	Title             string          `json:"title"`
	WorkEmail         string          `json:"work_email"`
	GithubURL         string          `json:"github_url"`
	Country           string          `json:"country"`
	State             string          `json:"state"`
	City              string          `json:"city"`
	Sources           *[]PersonSource `json:"sources"`
	ConfirmedAccounts *[]string       `json:"confirmed_accounts"`
	Seniority         string          `json:"seniority"`
	Department        string          `json:"department"`
}

type PersonSource struct {
	Provider   string `json:"provider"`
	Confidence string `json:"confidence"`
	Status     string `json:"status"`
	LastSeen   string `json:"last_seen"`
}
