// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Preseed struct {
	Confidence  *float64 `json:"confidence"`
	NeedsReview *bool    `json:"needsReview"`
	Type        string   `json:"type"`
	Title       string   `json:"title"`
	Value       string   `json:"value"`
	Capability  string   `json:"capability"`
}
