// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Preseed struct {
	Capability []string `json:"capability"`
	Type       string   `json:"type"`
	Title      string   `json:"title"`
	Value      string   `json:"value"`
}
