// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Preseed struct {
	Confidences []Confidence `json:"confidences"`
	Confidence  *int         `json:"confidence"`
	NeedsReview *bool        `json:"needsReview"`
	Capability  []string     `json:"capability"`
	Type        string       `json:"type"`
	Title       string       `json:"title"`
	Value       string       `json:"value"`
}
