// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Proof struct {
	Format   string         `json:"format"`
	Sections []ProofSection `json:"sections"`
}

type ProofSection struct {
	Title    string         `json:"title"`
	Elements []ProofElement `json:"elements"`
}

type ProofElement struct {
	Type         string             `json:"type"`
	Heading      *ProofHeading      `json:"heading"`
	Paragraph    *ProofParagraph    `json:"paragraph"`
	Group        *ProofGroup        `json:"group"`
	KeyValue     *ProofKeyValue     `json:"key_value"`
	Table        *ProofTable        `json:"table"`
	List         *ProofList         `json:"list"`
	CodeBlock    *ProofCodeBlock    `json:"code_block"`
	CodeSnippet  *ProofCodeSnippet  `json:"code_snippet"`
	HTTPExchange *ProofHTTPExchange `json:"http_exchange"`
	Banner       *ProofBanner       `json:"banner"`
	Metric       *ProofMetric       `json:"metric"`
	Reference    *ProofReference    `json:"reference"`
	Image        *ProofImage        `json:"image"`
	Timeline     *ProofTimeline     `json:"timeline"`
}

type ProofHeading struct {
	Level int    `json:"level"`
	Text  string `json:"text"`
}

type ProofParagraph struct {
	Text     string `json:"text"`
	Markdown bool   `json:"markdown"`
}

type ProofGroup struct {
	Title    string         `json:"title"`
	Elements []ProofElement `json:"elements"`
}

type ProofKeyValue struct {
	Rows []ProofKeyValueRow `json:"rows"`
}

type ProofKeyValueRow struct {
	Key      string `json:"key"`
	Value    string `json:"value"`
	Copyable bool   `json:"copyable"`
	Href     string `json:"href"`
	Severity string `json:"severity"`
}

type ProofTable struct {
	Columns []ProofTableColumn  `json:"columns"`
	Rows    []map[string]string `json:"rows"`
}

type ProofTableColumn struct {
	Key   string `json:"key"`
	Label string `json:"label"`
}

type ProofList struct {
	Style string          `json:"style"`
	Items []ProofListItem `json:"items"`
}

type ProofListItem struct {
	Label    string `json:"label"`
	Sublabel string `json:"sublabel"`
	Value    string `json:"value"`
	Copyable bool   `json:"copyable"`
	Href     string `json:"href"`
}

type ProofCodeBlock struct {
	Language string `json:"language"`
	Content  string `json:"content"`
}

type ProofCodeSnippet struct {
	FilePath   string               `json:"file_path"`
	Language   string               `json:"language"`
	StartLine  int                  `json:"start_line"`
	Content    string               `json:"content"`
	Highlights []ProofCodeHighlight `json:"highlights"`
}

type ProofCodeHighlight struct {
	StartLine int    `json:"start_line"`
	EndLine   int    `json:"end_line"`
	Kind      string `json:"kind"`
}

type ProofHTTPExchange struct {
	Request  *ProofHTTPMessage `json:"request"`
	Response *ProofHTTPMessage `json:"response"`
}

type ProofHTTPMessage struct {
	Method     string            `json:"method"`
	URL        string            `json:"url"`
	StatusCode int               `json:"status_code"`
	Headers    []ProofHTTPHeader `json:"headers"`
	Body       string            `json:"body"`
	Encoding   string            `json:"encoding"`
	Truncated  bool              `json:"truncated"`
}

type ProofHTTPHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type ProofBanner struct {
	Severity string `json:"severity"`
	Title    string `json:"title"`
	Body     string `json:"body"`
}

type ProofMetric struct {
	Label    string `json:"label"`
	Value    string `json:"value"`
	Unit     string `json:"unit"`
	Subtext  string `json:"subtext"`
	Severity string `json:"severity"`
}

type ProofReference struct {
	Kind  string `json:"kind"`
	ID    string `json:"id"`
	Label string `json:"label"`
	URL   string `json:"url"`
}

type ProofImage struct {
	URL     string `json:"url"`
	DataURI string `json:"data_uri"`
	AltText string `json:"alt_text"`
	Caption string `json:"caption"`
}

type ProofTimeline struct {
	Entries []ProofTimelineEntry `json:"entries"`
}

type ProofTimelineEntry struct {
	Title     string `json:"title"`
	Subtitle  string `json:"subtitle"`
	Reference string `json:"reference"`
	Href      string `json:"href"`
}
