// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

type Repository struct {
	LastScanState map[string]string `json:"lastScanState"`
	URL           string            `json:"url"`
	Org           string            `json:"org"`
	Name          string            `json:"name"`
	Public        bool              `json:"public"`
	SelfHosted    bool              `json:"selfhosted"`
}
