// Code generated by capmodelgen; DO NOT EDIT.

package capmodel

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"unicode/utf8"
)

// SmartBytes preserves text as a plain JSON string and encodes binary content
// behind a "base64:" prefix. Keep this type in a self-contained source file:
// capmodelgen copies the complete file into the capability SDK because its
// json.Marshaler and json.Unmarshaler implementations are part of the wire
// contract.
type SmartBytes []byte

func (sb SmartBytes) MarshalJSON() ([]byte, error) {
	if len(sb) == 0 {
		return []byte(`""`), nil
	}

	if needsEncoding(sb) {
		encoded := make([]byte, base64.StdEncoding.EncodedLen(len(sb)))
		base64.StdEncoding.Encode(encoded, sb)
		return json.Marshal("base64:" + string(encoded))
	}

	return json.Marshal(string(sb))
}

func (sb *SmartBytes) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	if len(s) > 7 && s[:7] == "base64:" {
		decoded, err := base64.StdEncoding.DecodeString(s[7:])
		if err != nil {
			return err
		}
		*sb = decoded
		return nil
	}

	*sb = []byte(s)
	return nil
}

func needsEncoding(data []byte) bool {
	// The prefix is reserved by UnmarshalJSON. Encoding literal text that starts
	// with it prevents decode errors and silent changes during a round trip.
	if bytes.HasPrefix(data, []byte("base64:")) || !utf8.Valid(data) {
		return true
	}

	for _, c := range data {
		// Control characters (except tab, CR, LF which JSON can handle with escaping)
		if c < 32 && c != '\t' && c != '\n' && c != '\r' {
			return true
		}

		// DEL character
		if c == 127 {
			return true
		}
	}

	return false
}
